FROM centos:7
MAINTAINER Kazuya Takei


# Install python 3.6
RUN yum install -y epel-release
RUN yum localinstall -y https://centos7.iuscommunity.org/ius-release.rpm
RUN yum install -y \
        python36u python36u-pip python36u-devel \
    && ln -s /usr/bin/pip3.6 /usr/bin/pip
RUN pip install wheel
