version: '2'

services:
  py36:
    build:
      context: .
      dockerfile: Dockerfile.py36
    image: attakei/wheel-py36
  mysqlclient:
    depends_on:
      - py36
    image: attakei/wheel-py36
    environment:
      YUM_PACKAGES: mysql-devel
    volumes:
      - ./wheels:/wheels
    command: mysqlclient==1.3.12
  airflow:
    depends_on:
      - py36
    image: attakei/wheel-py36
    volumes:
      - ./wheels:/wheels
    command: apache-airflow==1.8.2
